insert into clubs (name, neighborhood, city, genre, dress_code, last_call, cover_tiers) values
  ('Sister Louisa''s Church', 'Edgewood Ave', 'Atlanta', 'Dive Bar / Variety', 'Casual', '2:30 AM',
    '[{"until": null, "price": 0}]'::jsonb),
  ('The Music Room', 'Edgewood Ave', 'Atlanta', 'Hip-Hop / Top 40', 'Dress to impress', '2:30 AM',
    '[{"until": "10:30 PM", "price": 0}, {"until": "12:00 AM", "price": 15}, {"until": null, "price": 25}]'::jsonb),
  ('Noni''s Bar & Deli', 'Edgewood Ave', 'Atlanta', 'Live Music / Bar', 'Casual', '2:00 AM',
    '[{"until": null, "price": 0}]'::jsonb),
  ('Blake''s on the Park', 'Midtown', 'Atlanta', 'Gay Bar', 'Casual', '2:30 AM',
    '[{"until": null, "price": 0}]'::jsonb),
  ('Red Chair Lounge', 'Midtown', 'Atlanta', 'Lounge / Gay Bar', 'Casual to upscale', '2:30 AM',
    '[{"until": "11:00 PM", "price": 0}, {"until": null, "price": 10}]'::jsonb),
  ('Halo Lounge', 'Midtown', 'Atlanta', 'Lounge / EDM', 'Upscale', '2:30 AM',
    '[{"until": "11:00 PM", "price": 0}, {"until": "12:30 AM", "price": 20}, {"until": null, "price": 30}]'::jsonb),
  ('Gold Room', 'Midtown', 'Atlanta', 'Hip-Hop', 'Dress to impress', '3:00 AM',
    '[{"until": "11:00 PM", "price": 10}, {"until": null, "price": 20}]'::jsonb),
  ('Tongue & Groove', 'Buckhead', 'Atlanta', 'Upscale / Hip-Hop', 'Upscale, no sneakers', '2:30 AM',
    '[{"until": "11:00 PM", "price": 0}, {"until": null, "price": 25}]'::jsonb),
  ('Havana Club Buckhead', 'Buckhead', 'Atlanta', 'Latin', 'Dress to impress', '2:30 AM',
    '[{"until": "11:30 PM", "price": 10}, {"until": null, "price": 20}]'::jsonb),
  ('Republic Lounge', 'Buckhead', 'Atlanta', 'Lounge / Top 40', 'Upscale', '2:30 AM',
    '[{"until": null, "price": 15}]'::jsonb),
  ('The EARL', 'East Atlanta Village', 'Atlanta', 'Live Music / Indie', 'Casual', '2:30 AM',
    '[{"until": null, "price": 10}]'::jsonb),
  ('Graveyard Tavern', 'East Atlanta Village', 'Atlanta', 'Dive Bar / Metal-Punk', 'Casual', '2:30 AM',
    '[{"until": null, "price": 0}]'::jsonb),
  ('Argosy', 'East Atlanta Village', 'Atlanta', 'Bar / Games', 'Casual', '2:30 AM',
    '[{"until": null, "price": 0}]'::jsonb);
